apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: easycrud-ingress
  namespace: student

spec:
  project: default

  source:
    repoURL: https://github.com/avi-devopshub/EasyCRUD.git
    targetRevision: main
    path: k8s/

  destination:
    server: https://kubernetes.default.svc
    namespace: student

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
#updated